### PR TITLE
Add Hello class

### LINKED ISSUE #2: Implement Hello.java
It needs a method public void hello(String message) that prints out the message

### PR DESCRIPTION
**Pull request by dabeah**
I've added a really cool class that you can use. What do you think @scatrin ?

:joy_cat: :joy_cat: :joy_cat: 

closes #2

### CODE REVIEW

**Comment by katrinsko** [comment]
Looks good! I need you to add a constructor that accepts a java.lang.OutputStream though. And to use that OutputStream when printing the message.

**Review by katrinsko — CHANGES_REQUESTED** [review]
Added a review

**Comment by dabeah** [comment]
Added a constructor as requested. Are you happy now? @scatrin

**Comment by katrinsko** [comment]
@dabeah I also need you to use the OutputStream instead of System.out :nerd_face:

**Comment by dabeah** [comment]
Using outputStream, please review @scatrin

**Review by katrinsko — APPROVED** [review]

**Comment by katrinsko** [comment]
:+1: :shipit:

**Pull request merged**
